# Generated by Django 5.1.7 on 2025-03-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailattempt',
            name='status',
            field=models.CharField(choices=[('DONE', 'Выполнена'), ('NOT_DONE', 'Не выполнена')], default='NOT_DONE', max_length=150, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='messagerecipient',
            name='middle_name',
            field=models.CharField(max_length=150, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='messagerecipient',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='messagerecipient',
            name='surname',
            field=models.CharField(max_length=150, verbose_name='Фамилия'),
        ),
    ]
