# Generated by Django 5.1.7 on 2025-04-03 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_alter_mailattempt_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ('time_of_first_send',), 'permissions': [('can_view_all_mailings', 'Может просматривать все рассылки')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.RenameField(
            model_name='mailattempt',
            old_name='answer',
            new_name='response',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='message_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='message_title',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='mailattempt',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Успех'), ('FAILED', 'Неуспешно')], max_length=150, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailings.message', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создана'), ('STARTED', 'Запущена'), ('COMPLETED', 'Завершена')], max_length=150, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='Почта')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=150, verbose_name='Отчество')),
                ('surname', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Получатель',
                'verbose_name_plural': 'Получатели',
            },
        ),
        migrations.AlterField(
            model_name='mailing',
            name='recipients',
            field=models.ManyToManyField(related_name='mailings', to='mailings.recipient'),
        ),
        migrations.DeleteModel(
            name='MessageRecipient',
        ),
    ]
