# Generated by Django 5.1.7 on 2025-04-07 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_alter_mailing_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ('time_of_first_send',), 'permissions': [('can_view_all_mailings', 'Может просматривать все рассылки'), ('can_view_all_clients', 'Может просматривать всех клиентов'), ('can_block_clients', 'Может блокировать всех клиентов'), ('can_block_mailings', 'Может отключать все рассылки')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('title',), 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
