# Generated by Django 5.1.7 on 2025-05-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0005_alter_mailing_recipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Заблокирован'),
        ),
    ]
